### ISSUE TITLE
디자인 관련 이슈

### ISSUE THREAD

**Issue by HoraceVelmont** [CienProject2014/OneLevel2D#38]
상단 메뉴를 눌러서 메뉴가 활성화되면 메뉴가 흰색으로 반전된다. 근데 메뉴의 글꼴이 흰색이라 메뉴 글씨가 보이지 않게된다. 글꼴을 바꾸거나 반전되는 색상을 바꿔보자

**Comment by ChoiJIN** [comment]
다른 작업 하다가 그냥 해결함.
