### ISSUE TITLE
이미지를 remove해도 해당 폴더에서는 이미지가 제거되지 않음

### ISSUE THREAD

**Issue by HoraceVelmont** [CienProject2014/OneLevel2D#40]
이미지를 import한 후 수정사항이 생겨서 포토샵으로 수정을 한뒤 수정한 부분을 반영하기 위하여 해당 이미지를 remove한뒤 다시 import해도 프로그램 내에서 그 이미지를 기억하고 있어서 수정 부분이 반영되지 않는다. 아마 remove를 눌러도 Assets폴더에 기존 이미지가 지워지지 않고 남아있어서인것 같다. 이미지 remove시 해당 폴더에서도 이미지를 지워주는것이 리소스 관리 측면에서 적절한것 같다.

**Comment by ChoiJIN** [comment]
완료

**Comment by HoraceVelmont** [comment]
읭 안지워지는데;

**Comment by HoraceVelmont** [comment]
프로젝트가 사용중일경우 remove가되어도 이미지자체는 지워지지않음
