### ISSUE TITLE
priority가 낮은 이미지는 움직일 수 없다.

### ISSUE THREAD

**Issue by HoraceVelmont** [CienProject2014/OneLevel2D#45]
이미지가 우선권이 뒤에 있는 경우 해당 이미지를 ComponentList에서 클릭해도 방향키로 이동이 안된다. 마우스로 이동하려 해도 우선권이 앞에있는 이미지들이 막아버린다. (투명 이미지라서 눈으로는 보이지만  투명한 이미지로 인식해버린다.) 즉 앞에 있는 이미지가 뒤에있는 이미지를 크기상 감싸버릴경우 뒤에 있는 이미지들은 이동시킬 방법이 없다. 앞에 있는 이미지들의 우선권을 뒤로 한뒤 움직여 주었다가 다시 우선권을 돌려주는 방법 뿐이다. ComponentList에서 해당 이미지를 누르면 방향키로 움직일 수 있는 기능만 있으면 이 문제가 해결될 것 같다.

**Comment by ChoiJIN** [comment]
커밋 로그를 잘못남겨서 안떴지만 해결
