### ISSUE TITLE
component로 변경할 경우 좌표가 다르게 설정됨

### ISSUE THREAD

**Issue by HoraceVelmont** [CienProject2014/OneLevel2D#47]
Image들은 지정한 좌표에 정상적으로 표기되는데 component는 이상한곳에(y축방향으로 위에) 위치해있음

**Comment by ChoiJIN** [comment]
OneLevel2D의 위치랑 게임상에서 보이는 위치가 다르다는 건가요? Export 오류?

**Comment by ChoiJIN** [comment]
테스트 해보았는데 같은 문제가 발생하지 않네요. 구체적으로 어떤 상황에서 그러는지 확인되면 다시 해결하겠습니다.
